# -*- coding: utf-8 -*-
"""Data visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZUcvkGuqwEN-REN4athkPgHghnJFNlF

# **Importing the Libraries:**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Reading the dataset:**"""

df=pd.read_csv('student_habits_cleaned.csv')
df=df.drop(columns=['total_hours','total_screen_time'])

"""# **Data Overview:**"""

df.shape

df.head()

df.info()

df.dtypes

df.describe()

df.columns

def data_info(data):

    """
    This function returns a DataFrame containing the summary information for each column
    """

    Names=[col for col in data]
    data_types=[data[col].dtype for col in data.columns]
    top_10_unique_values=[data[col].value_counts().head(10).index.to_list() for col in data.columns]
    nunique_values=[data[col].nunique() for col in data.columns]
    nulls=[data[col].isnull().sum() for col in data.columns]
    percent_of_Nulls= [data[col].isnull().sum()/len(data)*100 for col in data.columns]


    info_df=pd.DataFrame({'Name':Names,
                          'Data_Type':data_types,
                          'Top_10_Unique_Values':top_10_unique_values,
                          'Nunique_Values':nunique_values,
                          'Nulls':nulls,
                          'Percent_of_Nulls':percent_of_Nulls,
                          })
    return info_df

data_info(df)

"""# **Visualizing the data:**

**Distribution of the exam score:**
"""

plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x='exam_score',
    bins=20,
    kde=True
)

plt.title('Distribution of Exam Scores')
plt.xlabel('Exam Score')
plt.ylabel('Number of Students')

plt.show()

"the exam score is nearly a normal distribution !"

plt.figure(figsize=(8, 3))

sns.boxplot(
    data=df,
    x='exam_score'
)

plt.title('Boxplot of Exam Scores')
plt.xlabel('Exam Score')

plt.show()

"""**How does the average exam performance change across age :**"""

age_performance = df.groupby('age')['exam_score'].mean().reset_index()

plt.figure(figsize=(8, 5))
sns.lineplot(
    data=age_performance,
    x='age',
    y='exam_score',
    marker='o'
)

plt.title('Average Exam Score by Age')
plt.xlabel('Age')
plt.ylabel('Average Exam Score')
plt.show()

sns.barplot(
    data=age_performance,
    x='age',
    y='exam_score',
)

plt.title('Average Exam Score by Age')
plt.xlabel('Age')
plt.ylabel('Average Exam Score')
plt.show()

"""**now the for the most important feature (study_hours):**"""

plt.figure(figsize=(8,5))

sns.scatterplot(
    data=df,
    x='study_hours_per_day',
    y='exam_score',
)

plt.title('Relationship between Study Hours and Exam Score')
plt.xlabel('Study Hours')
plt.ylabel('Exam Score')
plt.show()

"""
the dataset obviously a positive very strong near perfect linear relationship
between the study hours and the final exam score as As expected !
     """

correlation = df['study_hours_per_day'].corr(df['exam_score'])

print(correlation)
" nearly 0.83 that means its a very strong correlation !! "

plt.figure(figsize=(8, 5))

sns.regplot(
    data=df,
    x='study_hours_per_day',
    y='exam_score',
    scatter_kws={'color': 'blue'},
    line_kws={'color': 'red'}
)

plt.title('Relationship between Study Hours and Exam Score')
plt.xlabel('Study Hours')
plt.ylabel('Exam Score')
plt.show()
"""
that clearly shows that we can draw a line that fits most of the data points , it
confirms more that the study hours correlates with the exam score almost linearly !!
"""

"""**getting the relationship between the attendance and the score:**"""

plt.figure(figsize=(8, 5))
sns.scatterplot(
    data=df,
    x='attendance_percentage',
    y='exam_score'
)

plt.title('Attendance Percentage vs Exam Score')
plt.xlabel('Attendance Percentage')
plt.ylabel('Exam Score')
plt.show()
"""
unlike the expected!
the attendance percentage does not correlate with the exam score at all !!
the data points are completely scattered and there is no clear pattern.
"""

attendance_corr=df['attendance_percentage'].corr(df['exam_score'])
print(attendance_corr)
" 0.09 correlation assures that Attendance has almost no linear relationship with exam score in this dataset ."

"""Study hours showed a very strong positive linear relationship (r ≈ 0.83)
with exam score, while attendance percentage showed almost
no linear relationship with exam score (r ≈ 0.09).

**getting the relationship between sleep_hours & exam score:**
"""

plt.figure(figsize=(8, 5))
sns.scatterplot(
    data=df,
    x='sleep_hours',
    y='exam_score'
)

plt.title('Sleep Hours vs Exam Score')
plt.xlabel('Sleep Hours')
plt.ylabel('Exam Score')
plt.show()

sleep_corr=df['sleep_hours'].corr(df['exam_score'])
print(sleep_corr)

"""**Getting the relationship between social hours & exam score:**"""

sns.scatterplot(
    data=df,
    x='social_media_hours',
    y='exam_score'
)

plt.title('social media hours vs Exam Score')
plt.xlabel('social hours')
plt.ylabel('Exam Score')
plt.show()

print(df['social_media_hours'].corr(df['exam_score']))

"""**Getting the relationship between netflix hours & exam score:**"""

plt.figure(figsize=(8,5))

sns.scatterplot(
    data=df,
    x='netflix_hours',
    y='exam_score'
)

plt.title('Netflix Hours vs Exam Score')
plt.xlabel('Netflix Hours')
plt.ylabel('Exam Score')
plt.show()

"""
the data is scattered and theres no fixed linear relationship between them , the dataset
initially the scatterplot shows that the relation appears to be a negative weak correlation
"""

print(df['netflix_hours'].corr(df['exam_score']))
" r=-0.1717 that imply theres a weak negative relationship between the netflix hours and the exam score. "

"""**Relation between exercise_frequency and the exam score:**"""

exercise_performance = df.groupby('exercise_frequency')['exam_score'].mean().reset_index()
sns.boxplot(
    data=df,
    x='exercise_frequency',
    y='exam_score'
)

plt.title('Exercise Frequency vs Exam Score')
plt.xlabel('Exercise Frequency per Week')
plt.ylabel('Exam Score')
plt.show()

sns.lineplot(
    data=exercise_performance,
    x='exercise_frequency',
    y='exam_score',
    marker='o'

)

plt.title('Exercise Frequency vs Exam Score')
plt.xlabel('Exercise Frequency per Week')
plt.ylabel('Exam Score')
plt.show()

"""There is no clear monotonic relationship between exercise frequency and exam score.
    The average score goes up and down irregularly.

**Mental health relation with the exam score:**
"""

mental_health_performance = (
    df.groupby('mental_health_rating')['exam_score']
      .mean()
      .reset_index()
)
plt.figure(figsize=(8, 5))
sns.lineplot(
    data=mental_health_performance,
    x='mental_health_rating',
    y='exam_score',
    marker='o'
    )


plt.title('Mental Health Rating vs Exam Score')
plt.xlabel('Mental Health Rating')
plt.ylabel('Exam Score')
plt.show()

"""
yes the relationship may nit be a perfect line but its a function that's increasing on it's domain
that clears the dataset shows a nearly moderate positive correlation between the mental health and the examscore .
"""

r = df['mental_health_rating'].corr(df['exam_score'])
print(r)
" r= 0.3215 that means there's a weak near moderate correlation between the mental health and the examscore ."

"""# **Categorical data:**

**the relation between the diet quality and the exam score:**
"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x='diet_quality',
    y='exam_score'
)

plt.title('Exam Score by Diet Quality')
plt.xlabel('Diet Quality')
plt.ylabel('Exam Score')
plt.show()

"""
Exam score distributions across diet quality groups were relatively similar, with no strong difference in their median scores,
This suggests that diet quality does not show a strong apparent relationship with exam performance in this dataset.
"""

"""**the relation between the gender and the exam score:**"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x='gender',
    y='exam_score'
)

plt.title('Exam Score by Gender')
plt.xlabel('Gender')
plt.ylabel('Exam Score')
plt.show()

"""
Exam scores were relatively similar across gender groups,
with Male and Female students showing very close median scores.
The Other category also had a comparable distribution,
suggesting that gender does not have a strong apparent association with exam performance in this dataset.
"""

"""**the relation between the internet quality & the exam score:**"""

sns.boxplot(
    data=df,
    x='internet_quality',
    y='exam_score'
)

plt.title('Exam Score by Internet Quality')
plt.xlabel('Internet Quality')
plt.ylabel('Exam Score')
plt.show()

"""
Students with good internet quality had the lowest median exam score,
while students with average and poor internet quality had very similar median scores.
The Good category also had the smallest IQR, indicating less variability in exam scores within this group. Overall,
internet quality does not show the expected positive relationship with exam performance in this dataset.
"""

"""**Relation between Parental Education Level & exam score:**"""

sns.boxplot(
    data=df,
    x='parental_education_level',
    y='exam_score'
)

plt.title('Exam Score by Parental Education Level')
plt.xlabel('Parental Education Level')
plt.ylabel('Exam Score')
plt.show()
"""

"""



"""#**Correlation matrix:**"""

numeric_df = df.select_dtypes(include='number')

correlation_matrix = numeric_df.corr()

plt.figure(figsize=(10, 8))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Heatmap')
plt.show()

correlations = (
    df.select_dtypes(include='number')
      .corr()['exam_score']
      .sort_values(ascending=False)
)

correlations

categorical_columns = [
    'gender',
    'part_time_job',
    'diet_quality',
    'parental_education_level',
    'internet_quality',
    'extracurricular_participation'
]

for col in categorical_columns:
    plt.figure(figsize=(7, 4))

    sns.countplot(
        data=df,
        x=col
    )

    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Number of Students')
    plt.xticks(rotation=20)

    plt.show()

